# Servidor
server.port=8080
server.servlet.context-path=/

# WebSocket
spring.websocket.message-byte-buffer-max-size=512000
spring.websocket.message-text-buffer-max-size=512000

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.celestialfury=DEBUG

# Recursos estaticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**